### ISSUE TITLE
Mismatch between mobile and desktop-/web wallets seed phrase length

### ISSUE THREAD

**Issue by olefasting** [karlsen-network/karlsen-mobile#13]
**Describe the bug**
The seed phrase (secret phrase in menu) is 24 words long while both the desktop- and web wallet expect a 12 word long phrase

**To Reproduce**
1. Open mobile menu and select 'Backup Secret Phrase', which gives you a 24 word secret phrase
2. Open wallet on desktop or web and select import wallet, which gives you a form expecting a 12 word phrase

**Expected behavior**
It should be possible to import a mobile wallet to web or desktop using the secret phrase

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Android 13 / OxygenOS 13.0
 - Device: OnePlus Nord2 5G
 - Karlsen Mobile version: 2.0.0

**Comment by olefasting** [comment]
To anyone stumbling in here from Google etc.: I have been made aware of the fact that the karlsend CLI can import wallets with 24 word phrases.

**Comment by Leon1777** [comment]
Yes, that's because our web and desktop wallet only support importing 12-word legacy import (derivation path `972`).
