### ISSUE TITLE
Biometrics not working/showing

### ISSUE THREAD

**Issue by guiseco** [karlsen-network/karlsen-mobile#8]
**Describe the bug**
 Even when selecting biometrics, the app always shows the screen asking for the password

**To Reproduce**
Go to Security - Auth Methods - Biometric

**Expected behavior**
Enter the app using your fingerprint

**Screenshots**
![Screenshot_2024-04-05-19-50-55-342_io karlsen mobilewallet](https://github.com/karlsen-network/karlsen-mobile/assets/11425400/7396c87a-f4e9-4665-baf4-741341bb2f34)
![Screenshot_2024-04-05-19-51-08-399_io karlsen mobilewallet](https://github.com/karlsen-network/karlsen-mobile/assets/11425400/4bb522dc-7802-4a95-9373-8437a4a610ec)

**Desktop**
 - OS and version: android 11
 - Device: redmi note 8T
 - Karlsen Mobile version: [e.g. 0.2.0]

**Additional context**
Thanks

**Comment by okilisan** [comment]
Hi guiseco, thx for reporting.
imho there is no bug
If the whole wallet is protected by a password as shown in your screenshot, you will have to type ths password everytime you lock the wallet.
the authentication method (biometric or pin) concerns only the transaction validation step
where you can use fingerprint or pin code to validate the transaction before sending to the network
Let us know.

**Comment by guiseco** [comment]
Ahhh, ok! Thank you for your time to see this issue.

Em ter., 9 de abr. de 2024 13:09, okilisan ***@***.***>
escreveu:

**Comment by guiseco** [comment]
I misunderstood the biometrics part. Thank you for your time.
